### ISSUE TITLE
What is this crap

### ISSUE THREAD

**Issue by pbaylis** [skannerdarkly/MyFavoriteRepo#1]
@skannerdarkly

**Comment by skannerdarkly** [comment]
lol. why are you tracking my activity on Github?

(this is a repo i used when training new hires just to walk them through some basics)

**Comment by pbaylis** [comment]
I didn’t realize I was… but it popped up on mine so I guess I was? Not stopping now.

I’ve started to use GH for project management with grad students… so far it works pretty well
